### ISSUE TITLE
letters get deleted while typing

### ISSUE THREAD

**Issue by healthforms** [saranrapjs/p2p-party-line#1]
weird feeling while typing a new message, where a ghost deletes or changes a word. it's spooky!

**Comment by saranrapjs** [comment]
ok i just fixed a bunch of stuff (unfortunately had to get rid of the fun chat name words) and _may_ have also fixed the typing issue...but unfortunately have no way to test b/c no one is awake & available at this hour!

**Comment by healthforms** [comment]
i'm working the record store again on friday, i'd be happy to run another chat session
